### ISSUE TITLE
Kurtosis meta-feature

### ISSUE THREAD

**Issue by janvanrijn** [openml/EvaluationEngine#12]
I have a feeling that it is calculated wrongly.

**Comment by mwever** [comment]
I corrected the expected results in the JUnit tests to be -6.0. However, the "bug" you may refer to is rather the imprecision of the double datatype in java. We should instead fix the tests to allow for slight variations with respect to the true expected value. In JUnit this is already pretty much standard that if you compare double with assertEquals you have 3 parameters: expected, actual and delta. Delta refers here to the maximum tolerated difference between expected and actual.

**Comment by mwever** [comment]
Problem solved with PR-33
