### ISSUE TITLE
confusion matrix makes no sense as evaluation measure

### ISSUE THREAD

**Issue by amueller** [openml/EvaluationEngine#28]
There's "confusion matrix" in the evaluation measure drop-down on the frontend. I'm not sure if that's a frontend issue or a backend issue. This makes no sense in the context of the leaderboard and is not computed anyway.

**Comment by janvanrijn** [comment]
frontend issue. confusion matrix is computed (although it does not have a scalar value)

In the API you can see the following results:
https://www.openml.org/api/v1/evaluation/list/function/confusion_matrix/limit/100

**Comment by amueller** [comment]
Can you move the issue to the OpenML repo? It looks like I can't.

**Comment by janvanrijn** [comment]
it should be moved

**Comment by joaquinvanschoren** [comment]
Thanks, Andreas. 
The bigger problem is that we don't select measures based on the task type. If you choose a regression task, you can still choose all classification measures:
https://www.openml.org/t/52948

There are 2 ways of solving this:
* Add logic to the frontend that says which measures make sense for which task type.
* Add this information to the API.

I would vastly prefer the second option. The first seems like a hack?

This is what the frontend currently gets back from the API:
https://www.openml.org/api/v1/evaluationmeasure/list

If we could filter evaluation measures on `task_type` and 'shape' (i.e. scalar or array), we could show the right measures at the right time. I think that would also be useful for other scenarios.

What do you think?

**Comment by janvanrijn** [comment]
> Add this information to the API.

Completely agreed to this one.

**Comment by amueller** [comment]
yeah I agree, would be good to have that in the API.
Also we should not show metrics on the frontend that are not computed.
