### ISSUE TITLE
OpenML Feature mismatch data

### ISSUE THREAD

**Issue by PGijsbers** [openml/EvaluationEngine#37]
The OpenML Dataset Features have their `nominal_values` normalized, while the data itself is not:

```python
import openml
dresses = openml.datasets.get_dataset(23381)
df, *_ = dresses.get_data(dataset_format="dataframe")
print(d.features[1].nominal_values)
print(df[d.features[1].name].unique())
```
output:
```
['Average', 'high', 'low', 'Medium', 'very-high']

['Low', 'High', 'Average', 'Medium', 'very-high', 'low', 'high', NaN]
Categories (7, object): ['Average' < 'high' < 'High' < 'low' < 'Low' < 'Medium' < 'very-high']
```

edit: This is a problem already in the XML as @mfeurer indicates below.

**Comment by PGijsbers** [comment]
I have a `features.xml` file dating `7.2.2021` which already has a missing categorical value in the header.

**Comment by PGijsbers** [comment]
Wondering if there are any updates. It affects WEKA frameworks in the AutoML benchmark (as we generate ARFF files per fold based on the OpenML Feature data). Of course we can work around this if need be, but since the original issue is with OpenML I'd rather see the fix there.

**Comment by mfeurer** [comment]
I just found that dataset [307](https://www.openml.org/d/307), which is part of the OpenML-CC18, also suffers from this issue. This makes working with the CC18 suite in Python harder.

**Comment by joaquinvanschoren** [comment]
@PGijsbers what is 'd' in the code example you posted? 

Update: nevermind, I guess you renamed 'dresses' to 'd'. If I do that consistently it works.

**Comment by joaquinvanschoren** [comment]
In the case of 307, the issue is in the class label, which is likely even worse...

```
d = openml.datasets.get_dataset(307)
df, *_ = d.get_data(dataset_format="dataframe")
print(d.features[12].nominal_values)
print(df[d.features[12].name].unique())
```

Out:
```
['hAd', 'hEd', 'hid', 'hOd', 'hUd', 'hYd']
['hid', 'hId', 'hEd', 'hAd', 'hYd', ..., 'hOd', 'hod', 'hUd', 'hud', 'hed']
Length: 11
```

**Comment by janvanrijn** [comment]
Some unit tests that I wanted to upload, but haven't gotten to do so due to the new GitHub Authentication method. 

```

	@Test
	public final void testCaseSensitiveFeaturesArffTextual() throws Exception {
		Instances data = client_read_live.getArffFromUrl(1910507);
		assertEquals("high", data.attribute(1).value(1));
		assertEquals("High", data.attribute(1).value(2));
		assertEquals("low", data.attribute(1).value(3));
		assertEquals("Low", data.attribute(1).value(4));
		
		assertEquals("Low", data.instance(0).stringValue(1));
		assertEquals("low", data.instance(154).stringValue(1));
	}
	
	@Test
	public final void testCaseSensitiveExtractorTextual() throws Exception {
		Instances data = client_read_live.getArffFromUrl(1910507);
		List<Feature> features = ExtractFeatures.getFeatures(data, "Class");
		List<String> featureNames = new ArrayList<String>(Arrays.asList(features.get(1).getNominalValues()));
		assertTrue(featureNames.contains("low"));
		assertTrue(featureNames.contains("Low"));
		assertTrue(featureNames.contains("high"));
		assertTrue(featureNames.contains("High"));
		
		assertTrue(xstream.toXML(features).indexOf("<oml:nominal_value>low</oml:nominal_value>") > 0);
		assertTrue(xstream.toXML(features).indexOf("<oml:nominal_value>Low</oml:nominal_value>") > 0);
	}
	

	@Test
	public final void testCaseSensitiveExtractorOnTest() throws Exception {
		DataSetDescription dsd = new DataSetDescription("test-case-sensitive", "test", "arff", "Class");
		int did = client_write_test.dataUpload(dsd, new File("data/test/datasets/casesensitive.arff"));
		DataSetDescription downloaded = client_read_test.dataGet(did);
		Instances data = client_read_test.getArffFromUrl(downloaded.getFile_id());
		List<Feature> features = ExtractFeatures.getFeatures(data, "Class");
		DataFeature datafeature = new DataFeature(did, Settings.EVALUATION_ENGINE_ID, features.toArray(new Feature[features.size()]));
		client_admin_test.dataFeaturesUpload(datafeature);
		System.err.println(did);
		DataFeature df = client_read_test.dataFeatures(did);
		List<String> featureNames = new ArrayList<String>(Arrays.asList(df.getFeatureMap().get("V3").getNominalValues()));
		assertTrue(featureNames.contains("low"));
		assertTrue(featureNames.contains("Low"));
		assertTrue(featureNames.contains("high"));
		assertTrue(featureNames.contains("High"));
	}
```

**Comment by janvanrijn** [comment]
Anyway, I spend the majority of tonight debugging this. 

I checked the following things:
a) Whether the Evaluation Engine properly extracts case-sensitive values. It does (first unit tests)
b) Whether the PHP call properly uploads all the received values. It does (final unit test, through java)
c) works nice on both live and test. 

So.. this brings us to a weird situation. There seems to be no real explanation why the features were not there. Last thing I checked whether it could have been something with the MYSQL table, and my guess is the following: In the time when these features were extracted, OpenML might have had an older version of MySQL, where the key-based system was case-insensitive. MySQL could have been updated to a version where this became case insensitive. 

I have reset the aforementioned dataset, and the evaluation engine (not updated) processed it now properly. Let's close this topic! Let me know if there are other datasets that need to be reset as well. Please reopen if any issue comes up.

**Comment by PGijsbers** [comment]
Thanks to everyone who spent time tracking this down across the stack.

@janvanrijn  KDD (1111), colleges (42727) and Kick (41162) were affected as well and looks like it might have been skipped in the reset. I ran the following script to double-check no other datasets in the AutoML benchmark are affected by this, but it could be ran on all openml datasets (with empty cache):

```python
import openml

datasets_to_check = openml.study.get_suite(271).data
faulty_datasets = []
for did in datasets_to_check:
    print("Checking", did)
    d = openml.datasets.get_dataset(did)
    df, *_ = d.get_data(dataset_format="dataframe",include_row_id=True, include_ignore_attribute=True)
    nominal_features = [f for f in d.features.values() if f.nominal_values]
    faulty_feature = [
        f for f in nominal_features
        if len(set(v for v in df[f.name].unique() if isinstance(v, str)) - set(f.nominal_values)) > 0   #  Find the mismatch
           and len(set(v.lower() for v in df[f.name].unique() if isinstance(v, str)) - set(v.lower() for v in f.nominal_values)) == 0  # Ensure it specifically has to do with case sensitivity
    ]
    if faulty_feature:
        print(f"Dataset {did} has faulty features {faulty_feature}")
        faulty_datasets.append(did)

print(faulty_datasets)

```

**Comment by joaquinvanschoren** [comment]
Thanks! I have pulled in a fix so that we easily reset datasets and I have reset these 3.
I'll try running your code in a Colab instance :)

**Comment by joaquinvanschoren** [comment]
@PGijsbers : does this script take into account missing values?
```df[f.name].unique()``` also returns 'NaN' as a unique value if there is any missing value in that column

**Comment by joaquinvanschoren** [comment]
E.g. dataset 23381 has this situation

**Comment by PGijsbers** [comment]
That should be what the `if isinstance(v, str))` is for. Does it raise a false positive for you?
